# buildspec.yml
version: 0.2


phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      - python get-pip.py
      - pip install docker-compose

  pre_build:
    commands:
     - curr_working_dir=`pwd`
     - echo $curr_working_dir
     - buil_command="docker build -t sample-repo" $curr_working_dir "/Dockerfile"
     - echo $buil_command
#    - aws ecr get-login --no-include-email --region ap-south-1


  build:
    commands:
#       - mvn clean
       -$buil_command
  post_build:
    commands:
      - docker tag sample-repo:latest 248944429617.dkr.ecr.ap-south-1.amazonaws.com/sample-repo:latest
      - docker push 248944429617.dkr.ecr.ap-south-1.amazonaws.com/sample-repo:latest