# buildspec.yml
version: 0.2
env:
  variables:
    command1: "docker build -t sample-repo "
    command2: "/Dockerfile"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      - python get-pip.py
      - pip install docker-compose

  pre_build:
    commands:
     - curr_working_dir=`pwd`
     - echo $curr_working_dir
     - docker_command= $command1 $curr_working_dir $command2

#    - aws ecr get-login --no-include-email --region ap-south-1


  build:
    commands:
#       - mvn clean
       - $docker_command
  post_build:
    commands:
      - docker tag sample-repo:latest 248944429617.dkr.ecr.ap-south-1.amazonaws.com/sample-repo:latest
      - docker push 248944429617.dkr.ecr.ap-south-1.amazonaws.com/sample-repo:latest